package works.lucidsoft.akari.applogoicon

import android.content.ComponentName
import android.content.pm.PackageManager
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * Bridges JS to PackageManager.setComponentEnabledSetting so the user
 * can switch between the default launcher entry and any pre-declared
 * activity-alias variant. Aliases live in AndroidManifest.xml and are
 * generated by the withAppLogoIcons Expo config plugin.
 *
 * The DONT_KILL_APP flag is critical — without it the OS terminates
 * the app the next time the launcher hands focus, which trashes
 * navigation state and any in-flight queries.
 */
class AppLogoIconModule(private val reactContext: ReactApplicationContext) :
    ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = "AppLogoIconBridge"

    /**
     * AndroidManifest activity-alias names live under the package's
     * applicationId. JS passes either "default" (the original launcher
     * entry) or the alias suffix (e.g. "classic") and we expand it
     * here.
     */
    private fun componentNameFor(id: String): ComponentName {
        val pkg = reactContext.packageName
        // The default launcher entry is whatever the manifest's main
        // activity is. By convention we declare `.MainActivity` for
        // the default and `.MainActivity<Variant>` for each alias.
        val target = if (id == "default" || id.isEmpty()) "MainActivity" else "MainActivity${id.replaceFirstChar { it.uppercase() }}"
        return ComponentName(pkg, "$pkg.$target")
    }

    @ReactMethod
    fun supportsAlternateIcons(promise: Promise) {
        // Android always supports the activity-alias technique on any
        // launcher that respects intent filters; report true so the JS
        // layer has a symmetric API with iOS.
        promise.resolve(true)
    }

    @ReactMethod
    fun getCurrentAlternateIconName(promise: Promise) {
        val pkgManager = reactContext.packageManager
        val pkg = reactContext.packageName
        // Walk the known component-enabled states and return the first
        // enabled alias name (or null if the default activity is the
        // active entry). Since we own the alias namespace, scanning the
        // small set is cheaper than tracking state in MMKV.
        val candidates = listOf("classic")
        for (id in candidates) {
            val cn = componentNameFor(id)
            val state = pkgManager.getComponentEnabledSetting(cn)
            if (state == PackageManager.COMPONENT_ENABLED_STATE_ENABLED) {
                promise.resolve(id)
                return
            }
        }
        promise.resolve(null)
    }

    @ReactMethod
    fun setAlternateIconName(name: String?, promise: Promise) {
        try {
            val pkgManager = reactContext.packageManager
            val target = if (name.isNullOrEmpty() || name == "default") "default" else name
            val allAliases = listOf("classic")

            // Disable every alias EXCEPT the target. The default
            // launcher (`MainActivity`) is left alone since disabling
            // it would orphan the app on a fresh install.
            for (id in allAliases) {
                if (id == target) continue
                pkgManager.setComponentEnabledSetting(
                    componentNameFor(id),
                    PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                    PackageManager.DONT_KILL_APP
                )
            }

            if (target == "default") {
                // Default mode: ensure MainActivity itself is on. If a
                // previous switch toggled it off we'd otherwise leave
                // the app launchable from no entry at all.
                pkgManager.setComponentEnabledSetting(
                    componentNameFor("default"),
                    PackageManager.COMPONENT_ENABLED_STATE_ENABLED,
                    PackageManager.DONT_KILL_APP
                )
            } else {
                // Enable the requested alias and disable the default
                // launcher so the user doesn't see two icons.
                pkgManager.setComponentEnabledSetting(
                    componentNameFor(target),
                    PackageManager.COMPONENT_ENABLED_STATE_ENABLED,
                    PackageManager.DONT_KILL_APP
                )
                pkgManager.setComponentEnabledSetting(
                    componentNameFor("default"),
                    PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                    PackageManager.DONT_KILL_APP
                )
            }
            promise.resolve(true)
        } catch (e: Exception) {
            promise.reject("set_failed", e.message ?: "Failed to set alternate icon", e)
        }
    }
}
