#import <React/RCTBridgeModule.h>
#import <UIKit/UIKit.h>

/**
 * Native bridge for switching iOS alternate app icons from JS.
 *
 * UIApplication exposes setAlternateIconName/supportsAlternateIcons
 * directly; this module just hops to the main queue (the API
 * requires it) and surfaces success/error as a promise back to JS.
 *
 * Generated by the withAppLogoIcons Expo config plugin; do not edit
 * the copy in ios/ directly — change the template under
 * apps/akari/plugins/withAppLogoIcons/native/ios/ and re-run
 * `npx expo prebuild --clean`.
 */
@interface AppLogoIconBridge : NSObject <RCTBridgeModule>
@end

@implementation AppLogoIconBridge

RCT_EXPORT_MODULE(AppLogoIconBridge);

+ (BOOL)requiresMainQueueSetup
{
    return NO;
}

RCT_EXPORT_METHOD(supportsAlternateIcons:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    dispatch_async(dispatch_get_main_queue(), ^{
        resolve(@([UIApplication sharedApplication].supportsAlternateIcons));
    });
}

RCT_EXPORT_METHOD(getCurrentAlternateIconName:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    dispatch_async(dispatch_get_main_queue(), ^{
        NSString *name = [UIApplication sharedApplication].alternateIconName;
        resolve(name ?: [NSNull null]);
    });
}

RCT_EXPORT_METHOD(setAlternateIconName:(NSString *)name
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    dispatch_async(dispatch_get_main_queue(), ^{
        // The system treats nil as "reset to primary icon"; "default"
        // is the JS-side keyword for that.
        NSString *target = ([name isEqualToString:@"default"] || name.length == 0) ? nil : name;
        UIApplication *app = [UIApplication sharedApplication];
        if (![app supportsAlternateIcons]) {
            reject(@"unsupported", @"This iOS build does not support alternate icons", nil);
            return;
        }
        NSString *current = app.alternateIconName;
        NSLog(@"[AppLogoIconBridge] requested='%@' current='%@' supports=%d",
              target ?: @"<primary>", current ?: @"<primary>", [app supportsAlternateIcons]);
        [app setAlternateIconName:target completionHandler:^(NSError * _Nullable error) {
            if (error != nil) {
                NSString *detail = [NSString stringWithFormat:@"%@ (domain=%@ code=%ld userInfo=%@)",
                                    error.localizedDescription, error.domain, (long)error.code, error.userInfo];
                NSLog(@"[AppLogoIconBridge] FAILED %@", detail);
                reject(@"set_failed", detail, error);
            } else {
                NSLog(@"[AppLogoIconBridge] OK target='%@'", target ?: @"<primary>");
                resolve(@YES);
            }
        }];
    });
}

@end
