name: lint

on:
  pull_request_target:
    paths-ignore:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - '**/docs/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    # Only run for org members OR if external PR is labeled as safe
    if: |
      github.event.pull_request.head.repo.full_name == github.repository ||
      contains(github.event.pull_request.labels.*.name, 'safe-to-preview')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.9.0
          cache: npm
      - run: npm ci
      - run: npm run lint
